export const __prod__ = process.env.NODE_ENV === "production";
export const DB_NAME = "tijera";
export const TEST_DB_NAME = "tijera";
export const COOKIE_NAME = "qid";
export const EMAIL_REGEX = /^[\w\.]+@\w+\.\w+$/;
export const USERNAME_REGEX = /^[\w\.]+$/;
export const MAX_FILE_SIZE = 1000000000;
export const MERCHANT_IMAGES_PATH = "/../../media/merchant_images/";
export const MERCHANT_LOGOS_PATH = "/../../media/merchant_logos/";
export const FOODITEM_IMAGES_PATH = "/../../media/fooditem_images/";
export const TOKEN_CONVERSION_RATE = 1.0;
